- add LSB stuff (#246910)

diff --git a/dictd.init b/dictd.init
--- a/dictd.init
+++ b/dictd.init
@@ -5,6 +5,17 @@
 # processname: dictd
 # config: /etc/dictd.conf
 
+### BEGIN INIT INFO
+# Provides: dictd
+# Required-Start: 
+# Required-Stop: 
+# Default-Start: 
+# Default-Stop: 0 1 2 4 6
+# Short-Description: start|stop|restart|try-restart|status|force-reload dictd
+# Description: control dictionary server which allows clients access to 
+#  dictionary definitions from a set of natural language dictionary databases
+### END INIT INFO
+
 # Source function library.
 . /etc/rc.d/init.d/functions
 
@@ -28,10 +39,11 @@ function start
 	   echo -n $"no dictionaries installed"
 	   echo_failure
 	   echo
-	   RETVAL=1
+	   RETVAL=6
 	fi
     else
-	echo "$0: cannot find $DICTD or it's not executable"
+		echo "$0: cannot find $DICTD or it's not executable"
+		RETVAL=1
     fi
 
     RETVAL=${RETVAL:-$?}
@@ -42,10 +54,9 @@ function stop
 {
     echo -n $"Shutting down $prog: "
     killproc $prog
+	RETVAL=$?
     echo
     rm -f $LOCKFILE
-
-    RETVAL=0
 }
 
 function restart
@@ -60,9 +71,18 @@ case "$1" in
 		;;
     stop)	stop
 		;;
-    restart)	restart
+    restart | force-reload)	restart
 		;;
-    condrestart)
+    reload)
+		killproc $prog -HUP
+		RETVAL=$?
+		;;
+    force-reload)
+		killproc $prog -USR1
+		killproc $prog -HUP
+		RETVAL=$?
+		;;
+    try-restart | condrestart )
 		RETVAL=0
 		test -f $LOCKFILE && restart
 		;;
@@ -71,7 +91,7 @@ case "$1" in
 		RETVAL=$?
 		;;
     *)
-		echo $"Usage: $0 {start|stop|restart|condrestart|status}"
+		echo $"Usage: $0 {start|stop|restart|try-restart|condrestart|reload|force-reloadstatus}"
 		exit 1
 		;;
 esac
